import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Auth | Amazon Clone',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="min-h-screen flex items-center justify-center bg-amazon_light">
      {children}
    </div>
  );
}
