import type { Metadata } from 'next';
import 'swiper/css';

import Navbar from '@/components/Shared/Header/Navbar';
import { CartProvider } from '@/context/CartContext';

export const metadata: Metadata = {
  title: 'Amazon Clone',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <CartProvider>
      <Navbar />
      {children}
    </CartProvider>
  );
}
